services:
  dbhost:
    image: mariadb
    environment:
      MYSQL_DATABASE: littil
      MYSQL_USER: littil
      MYSQL_PASSWORD: littil
      MYSQL_ROOT_PASSWORD: littil
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: ghcr.io/devoxx4kids-npo/littil-backend:${LITTIL_BACKEND_VERSION:-latest}
    depends_on:
      dbhost:
        condition: service_healthy
      mailhog:
        condition: service_started
    volumes:
      - type: bind
        source: ./docker/backend
        target: /app
    environment:
      - QUARKUS_BANNER_ENABLED=true
      - CLOUDWATCH_ENABLED=false
      - LITTIL_DEV_DATA=true
      - LITTIL_DEV_DATA_FILE=/app/dev-users.csv
      - DATASOURCE_HOST=dbhost
      - HTTP_CORS_ORIGINS=http://localhost:4200
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_TENANT=${OIDC_TENANT}
      - M2M_CLIENT_ID=${M2M_CLIENT_ID}
      - M2M_CLIENT_SECRET=${M2M_CLIENT_SECRET}
      - QUARKUS_MAILER_MOCK=false
      - QUARKUS_MAILER_PORT=1025
      - QUARKUS_MAILER_SSL=false
      - SMTP_HOST=mailhog
      - SMTP_USERNAME=username
      - SMTP_PASSWORD=password
      - QUARKUS_LOG_CATEGORY__ORG_LITTIL__LEVEL=DEBUG
    ports:
      - "8080:8080"
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # Expose SMTP server
      - "8025:8025" # Expose Web UI
