services:
  dbhost:
    image: mariadb
    environment:
      MYSQL_DATABASE: littil
      MYSQL_USER: littil
      MYSQL_PASSWORD: littil
      MYSQL_ROOT_PASSWORD: littil
    ports:
      - "3306:3306"
  backend:
    image: ghcr.io/devoxx4kids-npo/littil-backend:${LITTIL_BACKEND_VERSION:-latest}
    depends_on:
      - dbhost
    environment:
      - QUARKUS_BANNER_ENABLED=true
      - CLOUDWATCH_ENABLED=false
      - LITTIL_DEV_DATA=true
      - DATASOURCE_HOST=dbhost
      - HTTP_CORS_ORIGINS=http://localhost:4200
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_TENANT=${OIDC_TENANT}
      - M2M_CLIENT_ID=${M2M_CLIENT_ID}
      - M2M_CLIENT_SECRET=${M2M_CLIENT_SECRET}
      - SMTP_HOST=smtp-stub.local
      - SMTP_USERNAME=username
      - SMTP_PASSWORD=password
    ports:
      - "8080:8080"
